//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafNwindQuery.Module.BusinessObjects.Northwind
{

    [NonPersistent]
    public partial class AlphabeticalListOfProducts : XPLiteObject
    {
        int fProductid;
        [Persistent(@"ProductID")]
        public int Productid
        {
            get { return fProductid; }
            set { SetPropertyValue<int>(nameof(Productid), ref fProductid, value); }
        }
        string fProductname;
        [Size(40)]
        [Persistent(@"ProductName")]
        public string Productname
        {
            get { return fProductname; }
            set { SetPropertyValue<string>(nameof(Productname), ref fProductname, value); }
        }
        int fSupplierid;
        [Persistent(@"SupplierID")]
        public int Supplierid
        {
            get { return fSupplierid; }
            set { SetPropertyValue<int>(nameof(Supplierid), ref fSupplierid, value); }
        }
        int fCategoryid;
        [Persistent(@"CategoryID")]
        public int Categoryid
        {
            get { return fCategoryid; }
            set { SetPropertyValue<int>(nameof(Categoryid), ref fCategoryid, value); }
        }
        string fQuantityperunit;
        [Size(20)]
        [Persistent(@"QuantityPerUnit")]
        public string Quantityperunit
        {
            get { return fQuantityperunit; }
            set { SetPropertyValue<string>(nameof(Quantityperunit), ref fQuantityperunit, value); }
        }
        decimal fUnitprice;
        [Persistent(@"UnitPrice")]
        public decimal Unitprice
        {
            get { return fUnitprice; }
            set { SetPropertyValue<decimal>(nameof(Unitprice), ref fUnitprice, value); }
        }
        short fUnitsinstock;
        [Persistent(@"UnitsInStock")]
        public short Unitsinstock
        {
            get { return fUnitsinstock; }
            set { SetPropertyValue<short>(nameof(Unitsinstock), ref fUnitsinstock, value); }
        }
        short fUnitsonorder;
        [Persistent(@"UnitsOnOrder")]
        public short Unitsonorder
        {
            get { return fUnitsonorder; }
            set { SetPropertyValue<short>(nameof(Unitsonorder), ref fUnitsonorder, value); }
        }
        short fReorderlevel;
        [Persistent(@"ReorderLevel")]
        public short Reorderlevel
        {
            get { return fReorderlevel; }
            set { SetPropertyValue<short>(nameof(Reorderlevel), ref fReorderlevel, value); }
        }
        bool fDiscontinued;
        public bool Discontinued
        {
            get { return fDiscontinued; }
            set { SetPropertyValue<bool>(nameof(Discontinued), ref fDiscontinued, value); }
        }
        string fCategoryname;
        [Size(15)]
        [Persistent(@"CategoryName")]
        public string Categoryname
        {
            get { return fCategoryname; }
            set { SetPropertyValue<string>(nameof(Categoryname), ref fCategoryname, value); }
        }
    }

}
