//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafNwindQuery.Module.BusinessObjects.Northwind
{

    [NonPersistent]
    public partial class CategorySalesFor1997 : XPLiteObject
    {
        string fCategoryname;
        [Size(15)]
        [Persistent(@"CategoryName")]
        public string Categoryname
        {
            get { return fCategoryname; }
            set { SetPropertyValue<string>(nameof(Categoryname), ref fCategoryname, value); }
        }
        decimal fCategorysales;
        [Persistent(@"CategorySales")]
        public decimal Categorysales
        {
            get { return fCategorysales; }
            set { SetPropertyValue<decimal>(nameof(Categorysales), ref fCategorysales, value); }
        }
    }

}
