//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafNwindQuery.Module.BusinessObjects.Northwind
{

    public partial class Categories : XPLiteObject
    {
        int fCategoryid;
        [Key(true)]
        [Persistent(@"CategoryID")]
        public int Categoryid
        {
            get { return fCategoryid; }
            set { SetPropertyValue<int>(nameof(Categoryid), ref fCategoryid, value); }
        }
        string fCategoryname;
        [Indexed(Name = @"CategoryName")]
        [Size(15)]
        [Persistent(@"CategoryName")]
        public string Categoryname
        {
            get { return fCategoryname; }
            set { SetPropertyValue<string>(nameof(Categoryname), ref fCategoryname, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        byte[] fPicture;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Picture
        {
            get { return fPicture; }
            set { SetPropertyValue<byte[]>(nameof(Picture), ref fPicture, value); }
        }
        [Association(@"ProductsReferencesCategories")]
        public XPCollection<Products> ProductsCollection { get { return GetCollection<Products>(nameof(ProductsCollection)); } }
    }

}
