//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafNwindQuery.Module.BusinessObjects.Northwind
{

    [Persistent(@"CustomerDemographics")]
    public partial class Customerdemographics : XPLiteObject
    {
        string fCustomertypeid;
        [Key]
        [Size(10)]
        [Persistent(@"CustomerTypeID")]
        public string Customertypeid
        {
            get { return fCustomertypeid; }
            set { SetPropertyValue<string>(nameof(Customertypeid), ref fCustomertypeid, value); }
        }
        string fCustomerdesc;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"CustomerDesc")]
        public string Customerdesc
        {
            get { return fCustomerdesc; }
            set { SetPropertyValue<string>(nameof(Customerdesc), ref fCustomerdesc, value); }
        }
    }

}
