//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafNwindQuery.Module.BusinessObjects.Northwind
{

    public partial class Employees : XPLiteObject
    {
        int fEmployeeid;
        [Key(true)]
        [Persistent(@"EmployeeID")]
        public int Employeeid
        {
            get { return fEmployeeid; }
            set { SetPropertyValue<int>(nameof(Employeeid), ref fEmployeeid, value); }
        }
        string fLastname;
        [Indexed(Name = @"LastName")]
        [Size(20)]
        [Persistent(@"LastName")]
        public string Lastname
        {
            get { return fLastname; }
            set { SetPropertyValue<string>(nameof(Lastname), ref fLastname, value); }
        }
        string fFirstname;
        [Size(10)]
        [Persistent(@"FirstName")]
        public string Firstname
        {
            get { return fFirstname; }
            set { SetPropertyValue<string>(nameof(Firstname), ref fFirstname, value); }
        }
        string fTitle;
        [Size(30)]
        public string Title
        {
            get { return fTitle; }
            set { SetPropertyValue<string>(nameof(Title), ref fTitle, value); }
        }
        string fTitleofcourtesy;
        [Size(25)]
        [Persistent(@"TitleOfCourtesy")]
        public string Titleofcourtesy
        {
            get { return fTitleofcourtesy; }
            set { SetPropertyValue<string>(nameof(Titleofcourtesy), ref fTitleofcourtesy, value); }
        }
        DateTime fBirthdate;
        [Persistent(@"BirthDate")]
        public DateTime Birthdate
        {
            get { return fBirthdate; }
            set { SetPropertyValue<DateTime>(nameof(Birthdate), ref fBirthdate, value); }
        }
        DateTime fHiredate;
        [Persistent(@"HireDate")]
        public DateTime Hiredate
        {
            get { return fHiredate; }
            set { SetPropertyValue<DateTime>(nameof(Hiredate), ref fHiredate, value); }
        }
        string fAddress;
        [Size(60)]
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        string fCity;
        [Size(15)]
        public string City
        {
            get { return fCity; }
            set { SetPropertyValue<string>(nameof(City), ref fCity, value); }
        }
        string fRegion;
        [Size(15)]
        public string Region
        {
            get { return fRegion; }
            set { SetPropertyValue<string>(nameof(Region), ref fRegion, value); }
        }
        string fPostalcode;
        [Indexed(Name = @"PostalCode")]
        [Size(10)]
        [Persistent(@"PostalCode")]
        public string Postalcode
        {
            get { return fPostalcode; }
            set { SetPropertyValue<string>(nameof(Postalcode), ref fPostalcode, value); }
        }
        string fCountry;
        [Size(15)]
        public string Country
        {
            get { return fCountry; }
            set { SetPropertyValue<string>(nameof(Country), ref fCountry, value); }
        }
        string fHomephone;
        [Size(24)]
        [Persistent(@"HomePhone")]
        public string Homephone
        {
            get { return fHomephone; }
            set { SetPropertyValue<string>(nameof(Homephone), ref fHomephone, value); }
        }
        string fExtension;
        [Size(4)]
        public string Extension
        {
            get { return fExtension; }
            set { SetPropertyValue<string>(nameof(Extension), ref fExtension, value); }
        }
        byte[] fPhoto;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Photo
        {
            get { return fPhoto; }
            set { SetPropertyValue<byte[]>(nameof(Photo), ref fPhoto, value); }
        }
        string fNotes;
        [Size(SizeAttribute.Unlimited)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>(nameof(Notes), ref fNotes, value); }
        }
        Employees fReportsto;
        [Persistent(@"ReportsTo")]
        [Association(@"EmployeesReferencesEmployees")]
        public Employees Reportsto
        {
            get { return fReportsto; }
            set { SetPropertyValue<Employees>(nameof(Reportsto), ref fReportsto, value); }
        }
        string fPhotopath;
        [Size(255)]
        [Persistent(@"PhotoPath")]
        public string Photopath
        {
            get { return fPhotopath; }
            set { SetPropertyValue<string>(nameof(Photopath), ref fPhotopath, value); }
        }
        [Association(@"EmployeesReferencesEmployees")]
        public XPCollection<Employees> EmployeesCollection { get { return GetCollection<Employees>(nameof(EmployeesCollection)); } }
        [Association(@"OrdersReferencesEmployees")]
        public XPCollection<Orders> OrdersCollection { get { return GetCollection<Orders>(nameof(OrdersCollection)); } }
    }

}
