//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafNwindQuery.Module.BusinessObjects.Northwind
{

    [NonPersistent]
    public partial class Invoices : XPLiteObject
    {
        string fShipname;
        [Size(40)]
        [Persistent(@"ShipName")]
        public string Shipname
        {
            get { return fShipname; }
            set { SetPropertyValue<string>(nameof(Shipname), ref fShipname, value); }
        }
        string fShipaddress;
        [Size(60)]
        [Persistent(@"ShipAddress")]
        public string Shipaddress
        {
            get { return fShipaddress; }
            set { SetPropertyValue<string>(nameof(Shipaddress), ref fShipaddress, value); }
        }
        string fShipcity;
        [Size(15)]
        [Persistent(@"ShipCity")]
        public string Shipcity
        {
            get { return fShipcity; }
            set { SetPropertyValue<string>(nameof(Shipcity), ref fShipcity, value); }
        }
        string fShipregion;
        [Size(15)]
        [Persistent(@"ShipRegion")]
        public string Shipregion
        {
            get { return fShipregion; }
            set { SetPropertyValue<string>(nameof(Shipregion), ref fShipregion, value); }
        }
        string fShippostalcode;
        [Size(10)]
        [Persistent(@"ShipPostalCode")]
        public string Shippostalcode
        {
            get { return fShippostalcode; }
            set { SetPropertyValue<string>(nameof(Shippostalcode), ref fShippostalcode, value); }
        }
        string fShipcountry;
        [Size(15)]
        [Persistent(@"ShipCountry")]
        public string Shipcountry
        {
            get { return fShipcountry; }
            set { SetPropertyValue<string>(nameof(Shipcountry), ref fShipcountry, value); }
        }
        string fCustomerid;
        [Size(5)]
        [Persistent(@"CustomerID")]
        public string Customerid
        {
            get { return fCustomerid; }
            set { SetPropertyValue<string>(nameof(Customerid), ref fCustomerid, value); }
        }
        string fCustomername;
        [Size(40)]
        [Persistent(@"CustomerName")]
        public string Customername
        {
            get { return fCustomername; }
            set { SetPropertyValue<string>(nameof(Customername), ref fCustomername, value); }
        }
        string fAddress;
        [Size(60)]
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        string fCity;
        [Size(15)]
        public string City
        {
            get { return fCity; }
            set { SetPropertyValue<string>(nameof(City), ref fCity, value); }
        }
        string fRegion;
        [Size(15)]
        public string Region
        {
            get { return fRegion; }
            set { SetPropertyValue<string>(nameof(Region), ref fRegion, value); }
        }
        string fPostalcode;
        [Size(10)]
        [Persistent(@"PostalCode")]
        public string Postalcode
        {
            get { return fPostalcode; }
            set { SetPropertyValue<string>(nameof(Postalcode), ref fPostalcode, value); }
        }
        string fCountry;
        [Size(15)]
        public string Country
        {
            get { return fCountry; }
            set { SetPropertyValue<string>(nameof(Country), ref fCountry, value); }
        }
        string fSalesperson;
        [Size(31)]
        public string Salesperson
        {
            get { return fSalesperson; }
            set { SetPropertyValue<string>(nameof(Salesperson), ref fSalesperson, value); }
        }
        int fOrderid;
        [Persistent(@"OrderID")]
        public int Orderid
        {
            get { return fOrderid; }
            set { SetPropertyValue<int>(nameof(Orderid), ref fOrderid, value); }
        }
        DateTime fOrderdate;
        [Persistent(@"OrderDate")]
        public DateTime Orderdate
        {
            get { return fOrderdate; }
            set { SetPropertyValue<DateTime>(nameof(Orderdate), ref fOrderdate, value); }
        }
        DateTime fRequireddate;
        [Persistent(@"RequiredDate")]
        public DateTime Requireddate
        {
            get { return fRequireddate; }
            set { SetPropertyValue<DateTime>(nameof(Requireddate), ref fRequireddate, value); }
        }
        DateTime fShippeddate;
        [Persistent(@"ShippedDate")]
        public DateTime Shippeddate
        {
            get { return fShippeddate; }
            set { SetPropertyValue<DateTime>(nameof(Shippeddate), ref fShippeddate, value); }
        }
        string fShippername;
        [Size(40)]
        [Persistent(@"ShipperName")]
        public string Shippername
        {
            get { return fShippername; }
            set { SetPropertyValue<string>(nameof(Shippername), ref fShippername, value); }
        }
        int fProductid;
        [Persistent(@"ProductID")]
        public int Productid
        {
            get { return fProductid; }
            set { SetPropertyValue<int>(nameof(Productid), ref fProductid, value); }
        }
        string fProductname;
        [Size(40)]
        [Persistent(@"ProductName")]
        public string Productname
        {
            get { return fProductname; }
            set { SetPropertyValue<string>(nameof(Productname), ref fProductname, value); }
        }
        decimal fUnitprice;
        [Persistent(@"UnitPrice")]
        public decimal Unitprice
        {
            get { return fUnitprice; }
            set { SetPropertyValue<decimal>(nameof(Unitprice), ref fUnitprice, value); }
        }
        short fQuantity;
        public short Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<short>(nameof(Quantity), ref fQuantity, value); }
        }
        float fDiscount;
        public float Discount
        {
            get { return fDiscount; }
            set { SetPropertyValue<float>(nameof(Discount), ref fDiscount, value); }
        }
        decimal fExtendedprice;
        [Persistent(@"ExtendedPrice")]
        public decimal Extendedprice
        {
            get { return fExtendedprice; }
            set { SetPropertyValue<decimal>(nameof(Extendedprice), ref fExtendedprice, value); }
        }
        decimal fFreight;
        public decimal Freight
        {
            get { return fFreight; }
            set { SetPropertyValue<decimal>(nameof(Freight), ref fFreight, value); }
        }
    }

}
