//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafNwindQuery.Module.BusinessObjects.Northwind
{

    [Persistent(@"Order Details")]
    public partial class OrderDetails : XPLiteObject
    {
        decimal fUnitprice;
        [Persistent(@"UnitPrice")]
        [ColumnDbDefaultValue("((0))")]
        public decimal Unitprice
        {
            get { return fUnitprice; }
            set { SetPropertyValue<decimal>(nameof(Unitprice), ref fUnitprice, value); }
        }
        short fQuantity;
        [ColumnDbDefaultValue("((1))")]
        public short Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<short>(nameof(Quantity), ref fQuantity, value); }
        }
        float fDiscount;
        [ColumnDbDefaultValue("((0))")]
        public float Discount
        {
            get { return fDiscount; }
            set { SetPropertyValue<float>(nameof(Discount), ref fDiscount, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("OrderID")]
            public int Orderid { get; set; }
            [Persistent("ProductID")]
            public int Productid { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
