//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafNwindQuery.Module.BusinessObjects.Northwind
{

    [NonPersistent]
    public partial class ProductsByCategory : XPLiteObject
    {
        string fCategoryname;
        [Size(15)]
        [Persistent(@"CategoryName")]
        public string Categoryname
        {
            get { return fCategoryname; }
            set { SetPropertyValue<string>(nameof(Categoryname), ref fCategoryname, value); }
        }
        string fProductname;
        [Size(40)]
        [Persistent(@"ProductName")]
        public string Productname
        {
            get { return fProductname; }
            set { SetPropertyValue<string>(nameof(Productname), ref fProductname, value); }
        }
        string fQuantityperunit;
        [Size(20)]
        [Persistent(@"QuantityPerUnit")]
        public string Quantityperunit
        {
            get { return fQuantityperunit; }
            set { SetPropertyValue<string>(nameof(Quantityperunit), ref fQuantityperunit, value); }
        }
        short fUnitsinstock;
        [Persistent(@"UnitsInStock")]
        public short Unitsinstock
        {
            get { return fUnitsinstock; }
            set { SetPropertyValue<short>(nameof(Unitsinstock), ref fUnitsinstock, value); }
        }
        bool fDiscontinued;
        public bool Discontinued
        {
            get { return fDiscontinued; }
            set { SetPropertyValue<bool>(nameof(Discontinued), ref fDiscontinued, value); }
        }
    }

}
