//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafNwindQuery.Module.BusinessObjects.Northwind
{

    [NonPersistent]
    public partial class ProductsAboveAveragePrice : XPLiteObject
    {
        string fProductname;
        [Size(40)]
        [Persistent(@"ProductName")]
        public string Productname
        {
            get { return fProductname; }
            set { SetPropertyValue<string>(nameof(Productname), ref fProductname, value); }
        }
        decimal fUnitprice;
        [Persistent(@"UnitPrice")]
        public decimal Unitprice
        {
            get { return fUnitprice; }
            set { SetPropertyValue<decimal>(nameof(Unitprice), ref fUnitprice, value); }
        }
    }

}
