//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafNwindQuery.Module.BusinessObjects.Northwind
{

    public partial class Region : XPLiteObject
    {
        int fRegionid;
        [Key]
        [Persistent(@"RegionID")]
        public int Regionid
        {
            get { return fRegionid; }
            set { SetPropertyValue<int>(nameof(Regionid), ref fRegionid, value); }
        }
        string fRegiondescription;
        [Size(50)]
        [Persistent(@"RegionDescription")]
        public string Regiondescription
        {
            get { return fRegiondescription; }
            set { SetPropertyValue<string>(nameof(Regiondescription), ref fRegiondescription, value); }
        }
        [Association(@"TerritoriesReferencesRegion")]
        public XPCollection<Territories> TerritoriesCollection { get { return GetCollection<Territories>(nameof(TerritoriesCollection)); } }
    }

}
