//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafNwindQuery.Module.BusinessObjects.Northwind
{

    public partial class Suppliers : XPLiteObject
    {
        int fSupplierid;
        [Key(true)]
        [Persistent(@"SupplierID")]
        public int Supplierid
        {
            get { return fSupplierid; }
            set { SetPropertyValue<int>(nameof(Supplierid), ref fSupplierid, value); }
        }
        string fCompanyname;
        [Indexed(Name = @"CompanyName")]
        [Size(40)]
        [Persistent(@"CompanyName")]
        public string Companyname
        {
            get { return fCompanyname; }
            set { SetPropertyValue<string>(nameof(Companyname), ref fCompanyname, value); }
        }
        string fContactname;
        [Size(30)]
        [Persistent(@"ContactName")]
        public string Contactname
        {
            get { return fContactname; }
            set { SetPropertyValue<string>(nameof(Contactname), ref fContactname, value); }
        }
        string fContacttitle;
        [Size(30)]
        [Persistent(@"ContactTitle")]
        public string Contacttitle
        {
            get { return fContacttitle; }
            set { SetPropertyValue<string>(nameof(Contacttitle), ref fContacttitle, value); }
        }
        string fAddress;
        [Size(60)]
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        string fCity;
        [Size(15)]
        public string City
        {
            get { return fCity; }
            set { SetPropertyValue<string>(nameof(City), ref fCity, value); }
        }
        string fRegion;
        [Size(15)]
        public string Region
        {
            get { return fRegion; }
            set { SetPropertyValue<string>(nameof(Region), ref fRegion, value); }
        }
        string fPostalcode;
        [Indexed(Name = @"PostalCode")]
        [Size(10)]
        [Persistent(@"PostalCode")]
        public string Postalcode
        {
            get { return fPostalcode; }
            set { SetPropertyValue<string>(nameof(Postalcode), ref fPostalcode, value); }
        }
        string fCountry;
        [Size(15)]
        public string Country
        {
            get { return fCountry; }
            set { SetPropertyValue<string>(nameof(Country), ref fCountry, value); }
        }
        string fPhone;
        [Size(24)]
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>(nameof(Phone), ref fPhone, value); }
        }
        string fFax;
        [Size(24)]
        public string Fax
        {
            get { return fFax; }
            set { SetPropertyValue<string>(nameof(Fax), ref fFax, value); }
        }
        string fHomepage;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"HomePage")]
        public string Homepage
        {
            get { return fHomepage; }
            set { SetPropertyValue<string>(nameof(Homepage), ref fHomepage, value); }
        }
        [Association(@"ProductsReferencesSuppliers")]
        public XPCollection<Products> ProductsCollection { get { return GetCollection<Products>(nameof(ProductsCollection)); } }
    }

}
