//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafNwindQuery.Module.BusinessObjects.Northwind
{

    public partial class Territories : XPLiteObject
    {
        string fTerritoryid;
        [Key]
        [Size(20)]
        [Persistent(@"TerritoryID")]
        public string Territoryid
        {
            get { return fTerritoryid; }
            set { SetPropertyValue<string>(nameof(Territoryid), ref fTerritoryid, value); }
        }
        string fTerritorydescription;
        [Size(50)]
        [Persistent(@"TerritoryDescription")]
        public string Territorydescription
        {
            get { return fTerritorydescription; }
            set { SetPropertyValue<string>(nameof(Territorydescription), ref fTerritorydescription, value); }
        }
        Region fRegionid;
        [Persistent(@"RegionID")]
        [Association(@"TerritoriesReferencesRegion")]
        public Region Regionid
        {
            get { return fRegionid; }
            set { SetPropertyValue<Region>(nameof(Regionid), ref fRegionid, value); }
        }
    }

}
